---

jo_image_tag: 19.2.2
jo_dmapi_namespace: data-manager-api-production

jo_ingress_domain: squonk.it
jo_ingress_tls_secret: data-manager-api-tls
jo_namespaces: data-manager-api-production

jo_kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
