---

- name: Deploy CRD
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'crd.yaml.j2') }}"
    wait: yes

- name: Deploy Data Manager Material
  kubernetes.core.k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
  loop:
  - rbac-data-manager
  - configmap-data-manager

- name: Deploy objects to operator Namespace ({{ jo_namespace }})
  kubernetes.core.k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
  loop:
  - namespace
  - sa
  - rbac
  - deployment
