---

# A ply to deploy objects to the chosen Data Manager namespace.
# In this case it's a Role and RoleBinding

- name: Prep
  ansible.builtin.include_tasks: prep.yaml

# Check the Data Manager Namespace and Service Account exists...

- name: Deploy DataManager RBAC objects
  module_defaults:
    group/k8s:
      kubeconfig: "{{ jo_kubeconfig }}"
  block:

  - name: Patch the Data Manager ({{ jo_dmapi_namespace }})
    ansible.builtin.include_tasks: dm-patch.yaml
