---

# A ply to deploy objects to the chosen Data Manager namespace.
# In this case it's a Role and RoleBinding

- name: Prep
  ansible.builtin.include_tasks: prep.yaml

# Check the Data Manager Namespace and Service Account exists...

- name: Display namespace
  ansible.builtin.debug:
    var: jo_dmapi_namespace

- name: Deploy DataManager RBAC objects (kubeconfig)
  when: jo_kubeconfig != 'SetMe'
  module_defaults:
    group/k8s:
      kubeconfig: "{{ jo_kubeconfig }}"
  block:

  - name: Patch the Data Manager (kubeconfig)
    ansible.builtin.include_tasks: dm-patch.yaml

- name: Deploy DataManager RBAC objects (k8s API)
  when: jo_kubeconfig == 'SetMe'
  block:

  - name: Patch the Data Manager (k8s API)
    ansible.builtin.include_tasks: dm-patch.yaml
