---

# Check the Data Manager Namespace.
# If it's not present, there's no namespace material to remove.

- name: Get Data Manager Namespace ({{ jo_dmapi_namespace }})
  kubernetes.core.k8s_info:
    kind: Namespace
    name: "{{ jo_dmapi_namespace }}"
  register: ns_result

- name: Remove operator material
  when: ns_result.resources|length == 1
  block:

  - name: Remove operator Data Manager API RBAC
    kubernetes.core.k8s:
      definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
      wait: yes
      state: absent
    loop:
    - rbac-data-manager

- name: Remove operator Namespace
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'namespace.yaml.j2') }}"
    wait: yes
    state: absent

- name: Remove CRD
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'crd.yaml.j2') }}"
    wait: yes
    state: absent
